[package]
name = "cellular"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "cellular"
path = "src/lib.rs"

[features]
default = [
	"cli"
]
cli = [
	"clearscreen",
	"clap",
	"image",
	"webp-animation",
	"colored"
]

[dependencies]
rand = "0.9.2"
rayon = "1.11.0"
clearscreen = { version = "4.0.2", optional = true }
colored = { version = "3.0.0", optional = true }
image = { version = "0.25.9", optional = true }
webp-animation = { version = "0.9.0", optional = true }
clap = { version = "4.5.53", optional = true, features = ["derive"] }
