[package]
name = "rayon-ca"
description = "High-performance cellular automaton's implementation in Rust LIB with CLI app and WebP animation export."
version = "0.2.1"
edition = "2021"
keywords = [
	"cellular-automata",
	"rayon",
	"simulation",
	"cli",
	"parallel"
]
categories = [
	"games",
	"game-development",
	"simulation",
	"concurrency",
	"command-line-utilities"
]
documentation = "https://docs.rs/rayon-ca"
repository = "https://github.com/AlexMorgan3817/CellularAutomatonsRust"

license = "MIT"
license-file = "LICENSE"

exclude = [
	".cargo/",
	".github/",
	'.vscode/'
]

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "rayon_ca"
path = "src/lib.rs"

[features]
default = []
cli = [
	"clearscreen",
	"clap",
	"image",
	"webp-animation",
	"colored"
]

[dependencies]
rand = "0.9"
rayon = "1.11"
clearscreen = { version = "4.0.2", optional = true }
colored = { version = "3.0.0", optional = true }
image = { version = "0.25.9", optional = true }
webp-animation = { version = "0.9.0", optional = true }
clap = { version = "4.5.53", optional = true, features = ["derive"] }
